import { useCallback } from 'react';
import { useTranslation } from 'react-i18next';

const EN: Record<string, string> = {
  'Produção': 'Production',
  'Carga': 'Cargo',
  'Manutenção': 'Maintenance',
  'Segurança': 'Safety',
  'Outro': 'Other',
  'Subcontratado / visitante': 'Subcontractor / visitor',
  'Convés principal de carga': 'Cargo main deck',
  'Tanques de carga': 'Cargo tanks',
  'Casa de máquinas': 'Engine room',
  'Sala de bombas': 'Pump room',
  'EPI adequado (cabeça, face, respiratório)': 'Appropriate PPE (head, face, respiratory)',
  'EPI adequado (braços, mãos, corpo)': 'Appropriate PPE (arms, hands, body)',
  'EPI adequado (pernas e pés)': 'Appropriate PPE (legs and feet)',
  'Ferramentas / equipamentos usados corretamente': 'Tools / equipment correctly used',
  'Manuseio manual': 'Manual handling',
  'Procedimentos conhecidos e compreendidos': 'Procedures known and understood',
  'Procedimentos seguidos': 'Procedures followed',
  'Preparação do trabalho (PTW / TRA)': 'Work preparation (PTW / TRA)',
  'Intervenção (autoridade de parar o trabalho, tornar seguro)': 'Intervention (stop work authority, make safe)',
  'Comunicação efetiva / DDS': 'Effective communication / toolbox talk',
  'Mudança no ambiente de trabalho': 'Change in work environment',
  'Acesso e saída': 'Access and egress',
  'Organização / gestão de resíduos': 'Housekeeping / waste management',
  'Escorregoes e tropeços': 'Slips and trips',
  'Trabalho em altura': 'Work at height',
  'Objetos caídos': 'Dropped objects',
  'Gestão de cabos': 'Cable management',
  'Ventilação': 'Ventilation',
  'Ruído': 'Noise',
  'Iluminação': 'Lighting',
  'Produtos químicos e substâncias': 'Chemicals and substances',
  'Barreiras, sinalizações e avisos': 'Barriers, signs and notices',
  'Elétrico': 'Electrical',
  'Andaimes': 'Scaffolding',
  'Içamento e rigging': 'Lifting and rigging',
  'Solda e corte': 'Welding and cutting',
  'Ferramentas elétricas e manuais': 'Power and hand tools',
  'Ferramentas / equipamentos em boas condições': 'Tools / equipment in good condition',
  'Isolamentos aplicados': 'Isolations in place',
  'Operação': 'Running',
  'Gás não HC': 'Non HC gas',
  'Vapor': 'Steam',
  'Oleo HC': 'HC oil',
  'Oleo lubrificante': 'Lube oil',
  'Químicos': 'Chemicals',
  'Água produzida': 'Produced water',
  'Água': 'Water',
  'Conexão de instrumento': 'Instrument fitting',
  'Selo ou corpo do atuador': 'Actuator seal or body',
  'Trocador de calor': 'Heat exchanger',
  'Mangueiras flexíveis': 'Flexible hoses',
  'Corpo principal de tubulação / pipeline': 'Pipework / pipeline main body',
  'Conexão soldada': 'Welded connection',
  'Selo de válvula': 'Valve seal',
  'Corpo de válvula': 'Valve body',
  'Selo de bomba (incl. selo de eixo)': 'Pump seal (incl. shaft seal)',
  'Corpo de bomba': 'Pump body',
  'Instrumento de processo': 'Process instrument',
  'Tubing / conexão roscada': 'Tubing / threaded connection',
  'Outro equipamento': 'Other equipment',
  'Vibração': 'Vibration',
  'Corrosão sob isolamento': 'Corrosion under insulation',
  'Outra corrosão externa': 'Other external corrosion',
  'Corrosão interna': 'Internal corrosion',
  'Erosao': 'Erosion',
  'Impacto mecânico': 'Mechanical impact',
  'Tensão mecânica': 'Mechanical stress',
  'Sobrepressurização': 'Over-pressurization',
  'Falha de material': 'Material failure',
  'Falha catastrófica de equipamento': 'Equipment catastrophic failure',
  'Operação inadequada': 'Mal-operation',
  'Desgaste': 'Wear and tear',
  'Clima extremo': 'Extreme weather',
  'Não determinado': 'Not determined',
  'Limites operacionais seguros': 'Safe operating limits',
  'Travas de segurança / intertravamento': 'Safety locks / interlock',
  'Procedimentos disponíveis': 'Procedures available',
  'Desenhos atualizados (P&ID, PFD, diagramas)': 'Drawings up to date (P&ID, PFD, diagrams)',
  'Dados atualizados (ajustes, registros, informações)': 'Data up to date (settings, registers, information)',
  'Mangueiras temporárias / gestão de cabos': 'Temporary hoses / cable management',
  'Sempre usar duas barreiras para drenos e vents de hidrocarbonetos e químicos': 'Always use two barriers for hydrocarbon and chemical drains and vents',
  'Permanecer presente durante transferência crítica ou drenagem': 'Always remain in attendance during critical transfer or draining',
  'Aplicar medidas mitigadoras interinas em falha de equipamento crítico de segurança': 'Take interim mitigating measures in case of failure of safety critical equipment',
  'Em atividades de alto risco, seguir procedimentos e assinar cada etapa': 'For high-risk activities, follow procedures and sign off each step',
  'Percorrer a linha, verificar e validar qualquer mudança de alinhamento': 'Walk the line, verify and validate any line-up change',
  'Sempre usar MOC ao fazer uma mudança': 'Always use MOC when making a change',
  'Verificar estanqueidade completa após manutenção': 'Verify complete tightness after maintenance',
  'Confirmar equipamento sem pressão, drenado e com isolamento seguro antes de iniciar': 'Confirm equipment is pressure free, drained and isolated before starting',
  'Realizar MOC e instalar proteção contra refluxo ao conectar utilidades ao processo': 'Perform MOC and install backflow protection when connecting utilities to process',
  'Responder a alarmes críticos': 'Respond to critical alarms',
  'Condição insegura': 'Unsafe condition',
  'Ato inseguro': 'Unsafe act',
  'Comportamento seguro': 'Safe behavior',
  'Boa prática': 'Good practice',
  'Quase acidente': 'Near miss',
  'Segurança de processo': 'Process safety',
  'Linha de fogo': 'Line of fire',
  'Objeto queda / dropped object': 'Dropped object',
  'Queda de altura': 'Fall from height',
  'Movimentação de carga': 'Lifting operations',
  'Eletricidade': 'Electrical',
  'Pressão / linhas pressurizadas': 'Pressure / pressurized lines',
  'Incêndio / explosão': 'Fire / explosion',
  'LOTO / isolamento': 'LOTO / isolation',
  'Baixa': 'Low',
  'Média': 'Medium',
  'Alta': 'High',
  'Crítica': 'Critical',
  'Improvável': 'Unlikely',
  'Possível': 'Possible',
  'Provável': 'Likely',
  'Muito provável': 'Very likely',
  'Baixo': 'Low',
  'Médio': 'Medium',
  'Alto': 'High',
  'Crítico': 'Critical',
  'Aberta': 'Open',
  'Em andamento': 'In progress',
  'Concluída': 'Closed',
  'Não informado': 'Not informed',
  'Todos': 'All',
  'Comportamento / Condição': 'Behavior / Condition',
  'Segurança de Processo': 'Process Safety',
  'Modelo': 'Template',
  'Tipo de cartão': 'Card type',
  'Local': 'Location',
  'Identificação': 'Identification',
  'Observação': 'Observation',
  'Itens do cartão': 'Card items',
  'Risco e ação': 'Risk and action',
  'Tratativa': 'Action tracking',
  'Revisão': 'Review',
  'Conferência final': 'Final check',
  'Seguro': 'Safe',
  'Inseguro': 'Unsafe',
  'Risco': 'Risk',
  'Ações': 'Actions',
  'Data': 'Date',
  'Navio / local': 'Vessel / location',
  'Descrição': 'Description',
  'Status': 'Status',
  'Visualizar': 'View',
  'Editar tratativa': 'Edit action tracking',
  'Baixar PDF': 'Download PDF',
  'Excluir': 'Delete',
  'Observação atualizada': 'Observation updated',
  'A tratativa foi salva com sucesso.': 'The action tracking was saved successfully.',
  'Erro ao salvar': 'Error saving',
  'Não foi possível atualizar a observação.': 'The observation could not be updated.',
  'Observação excluída': 'Observation deleted',
  'O registro foi removido da lista.': 'The record was removed from the list.',
  'Erro ao excluir': 'Error deleting',
  'Não foi possível excluir a observação.': 'The observation could not be deleted.',
  'Relatórios de Observação de Segurança': 'Safety Observation Reports',
  'Registros enviados pelo formulário de observação, com tratativa e exportação.': 'Records submitted through the observation form, with action tracking and export.',
  'Total de registros': 'Total records',
  'Abertas': 'Open',
  'Críticas / fatalidade': 'Critical / fatality',
  'Com acompanhamento': 'With follow-up',
  'Filtros': 'Filters',
  'Buscar por navio, local, observador, descrição ou ação...': 'Search by vessel, location, observer, description or action...',
  'Registros': 'Records',
  'Carregando observações...': 'Loading observations...',
  'Nenhuma observação encontrada.': 'No observations found.',
  'Atualize o status, responsável, prazo e ações de acompanhamento.': 'Update status, owner, due date and follow-up actions.',
  'Risco residual': 'Residual risk',
  'Responsável': 'Responsible',
  'Prazo': 'Due date',
  'Ação recomendada': 'Recommended action',
  'Aprendizado': 'Learning',
  'Cancelar': 'Cancel',
  'Salvar': 'Save',
  'Excluir observação?': 'Delete observation?',
  'Essa ação remove o registro da base. Use apenas para duplicidades ou lançamentos incorretos.': 'This action removes the record from the database. Use it only for duplicates or incorrect entries.',
  'Detalhes da observação': 'Observation details',
  'Registro completo enviado pelo formulário de observação de segurança.': 'Complete record submitted through the safety observation form.',
  'Navio': 'Vessel',
  'Localização': 'Location',
  'Data e hora': 'Date and time',
  'Observador': 'Observer',
  'Departamento': 'Department',
  'Percepção de risco': 'Risk perception',
  'Ação imediata': 'Immediate action',
  'Navio obrigatório': 'Vessel required',
  'Selecione um navio no topo do sistema.': 'Select a vessel in the system header.',
  'Localização obrigatória': 'Location required',
  'Selecione ou cadastre a área onde aconteceu.': 'Select or register the area where it happened.',
  'Descrição obrigatória': 'Description required',
  'Descreva objetivamente o que foi observado.': 'Objectively describe what was observed.',
  'Sessão inválida': 'Invalid session',
  'Faça login novamente.': 'Please sign in again.',
  'Sem permissão': 'No permission',
  'Seu perfil não pode criar observações de segurança.': 'Your profile cannot create safety observations.',
  'Campos obrigatórios': 'Required fields',
  'Preencha área/local e descrição da observação.': 'Fill in area/location and observation description.',
  'Observação registrada': 'Observation recorded',
  'O cartão foi salvo com todos os campos do modelo selecionado.': 'The card was saved with all fields from the selected template.',
  'Obrigado pela sua observação': 'Thank you for your observation',
  'Seu cartão foi registrado com sucesso. Esse registro ajuda a fortalecer a cultura de segurança e a tratar riscos antes que eles evoluam.': 'Your card was successfully recorded. This record helps strengthen the safety culture and address risks before they escalate.',
  'Registrar nova observação': 'Record new observation',
  'Voltar ao Cartão com IA': 'Back to AI Observation Card',
  'Formulário de Observação de Segurança': 'Safety Observation Form',
  'Modelos Comportamento / Condição e Fundamentos de Segurança de Processo.': 'Behavior / Condition and Process Safety Fundamentals templates.',
  'Carregando navio': 'Loading vessel',
  'Nenhum navio disponível': 'No vessel available',
  'Acompanhamento requerido': 'Follow-up required',
  'Cartão de Observação com IA': 'Observation Card with AI',
  'Modelo do cartão': 'Card template',
  'Selecione o formulário físico correspondente.': 'Select the corresponding physical form.',
  'Cartão azul: comportamento, condição e equipamento.': 'Blue card: behavior, condition and equipment.',
  'Cartão laranja: W&S, causas, salvaguardas e PSF.': 'Orange card: W&S, causes, safeguards and PSF.',
  'Identificação e local': 'Identification and location',
  'Navio da conta, área cadastrada do navio e campos do cabeçalho do cartão.': 'Account vessel, registered vessel area and card header fields.',
  'Navio da conta': 'Account vessel',
  'Selecione um navio no topo': 'Select a vessel in the header',
  'Localização / outro local': 'Location / other place',
  'Selecione ou crie a área': 'Select or create the area',
  'Nome': 'Name',
  'Nome do observador': 'Observer name',
  'Onde aconteceu?': 'Where did it happen?',
  'Modo operacional': 'Operating mode',
  'Visita do gerente ao local': 'Manager site visit',
  'Descrição, ação e risco': 'Description, action and risk',
  'Campos narrativos e controle de acompanhamento / ordem de serviço.': 'Narrative fields and follow-up / work order controls.',
  'Descreva sua observação': 'Describe your observation',
  'Qual era o risco percebido?': 'What was the perceived risk?',
  'Descreva sua ação / discussão / intervenção': 'Describe your action / discussion / intervention',
  'Descreva a ação, conversa ou intervenção.': 'Describe the action, conversation or intervention.',
  'Consequência potencial': 'Potential consequence',
  'Pessoa informada': 'Person notified',
  'Supervisor, liderança, OIM...': 'Supervisor, leadership, OIM...',
  'Tipo de observação': 'Observation type',
  'Categoria de risco': 'Risk category',
  'Severidade': 'Severity',
  'Probabilidade': 'Likelihood',
  'Risco residual após a ação': 'Residual risk after the action',
  'Nível de risco': 'Risk level',
  'Ação definitiva ou melhoria': 'Final action or improvement',
  'Nome ou função': 'Name or role',
  'Ação de acompanhamento requerida': 'Follow-up action required',
  'Ordem de serviço requerida': 'Work order required',
  'Stop Work exercido': 'Stop Work exercised',
  'Potencial de fatalidade': 'Fatality potential',
  'Requer investigação': 'Requires investigation',
  'Requer CMMS': 'Requires CMMS',
  'Compartilhar em TBT': 'Share in TBT',
  'Cartão indicado': 'Nominated card',
  'Aprendizado compartilhável.': 'Shareable learning.',
  'Limpar': 'Clear',
  'Voltar': 'Back',
  'Salvar observação': 'Save observation',
  'Próximo': 'Next',
  'Comportamento / Condição / Equipamento': 'Behavior / Condition / Equipment',
  'Marque Seguro ou Inseguro para cada item do cartão azul.': 'Mark Safe or Unsafe for each blue-card item.',
  'Comportamento': 'Behavior',
  'Condição': 'Condition',
  'Equipamento': 'Equipment',
  'Vazamentos e exsudações (W&S)': 'Weeps and seeps (W&S)',
  'Tipo, volume, local do vazamento e causa principal do cartão laranja.': 'Type, volume, leak location and main cause from the orange card.',
  'Tipo e volume': 'Type and volume',
  'Distância do vazamento (m)': 'Distance from leak (m)',
  'Gotas por minuto': 'Drops per minute',
  'gotas/min': 'drops/min',
  'Local do vazamento': 'Leak location',
  'Causa principal': 'Main cause',
  'Salvaguardas e fundamentos de segurança de processo com Seguro / Inseguro.': 'Process safety safeguards and fundamentals with Safe / Unsafe.',
  'Principais salvaguardas de segurança de processo': 'Main process safety safeguards',
  'Fundamentos de segurança de processo (PSF)': 'Process Safety Fundamentals (PSF)',
  'Revisão antes do envio': 'Review before submission',
  'Confira os principais dados. Use Voltar para ajustar qualquer etapa.': 'Check the main data. Use Back to adjust any step.',
  'Onde aconteceu': 'Where it happened',
  'Tipo': 'Type',
  'Categoria': 'Category',
  'Ação / discussão / intervenção': 'Action / discussion / intervention',
  'Investigação requerida': 'Investigation required',
};

export function useSafetyObservationText() {
  const { i18n } = useTranslation();
  const isPortuguese = (i18n.language || '').toLowerCase().startsWith('pt');

  return useCallback((text: string) => {
    if (isPortuguese) return text;
    return EN[text] ?? text;
  }, [isPortuguese]);
}

export function translateOptions<T extends string>(
  options: ReadonlyArray<readonly [T, string]>,
  translate: (text: string) => string,
): Array<readonly [T, string]> {
  return options.map(([value, label]) => [value, translate(label)] as const);
}
